service: serverless-rest-api-with-rds

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    RDS_HOSTNAME: database-4.cgzpm2kh8ggg.us-east-1.rds.amazonaws.com
    RDS_USERNAME: admin
    RDS_PASSWORD: letmein1
    RDS_PORT: 3306

functions:

  create:
    handler: rds/create.handler
    events:
      - http:
          path: rds/
          method: post
          cors: true

  createStudent:
    handler: rds/student.handler
    events:
      - http:
          path: rds/student/
          method: post
          cors: true

  get:
    handler: rds/get.handler
    events:
      - http:
          path: rds/get/
          method: get
          cors: true
